### PR TITLE
Add CLI

### PR DESCRIPTION
**Pull request by arthurvr**
Ref https://github.com/datetime/current-day-number/issues/2.

### CODE REVIEW

**Comment by arthurvr** [comment]
@tunnckoCore ping?

**Comment by tunnckoCore** [comment]
Ping-pong.
Cool, thanks!

I'll merge and publish ASAP. :)

**Comment by arthurvr** [comment]
> I'll merge and publish ASAP. :)

@tunnckoCore friendly ping once again?

**Comment by tunnckoCore** [comment]
@arthurvr ooh thanks, mate. I totally forgot. :+1: 

Wait a bit :)

**Comment by tunnckoCore** [comment]
It's okey, but I think it should also handle and other cases.

**Comment by arthurvr** [comment]
> It's okey, but I think it should also handle and other cases.

Sure. I will update my PR.

**Comment by tunnckoCore** [comment]
Hm. But its interesting how to handle `'August 07, 2016` in cli ;d

**Comment by tunnckoCore** [comment]
Okey, great. :)

**Comment by arthurvr** [comment]
http://gyazo.com/f8e629c80cb2ea5641f251f3c017fecb, LGTY?

**Comment by arthurvr** [comment]
> Hm. But its interesting how to handle August 07, 2016 in cli ;d

What do you mean?

**Comment by tunnckoCore** [comment]
Haha, cool. Looks great.

**Comment by tunnckoCore** [comment]
@arthurvr released and published as `v1.0.6`

**Pull request merged**
